command:
  - "python"
  - "app.py"

env:
  - name: LAKEBASE_SECRET_SCOPE
    value: "database"
  - name: LAKEBASE_SECRET_KEY
    value: "lakebase-url"
  - name: TICKETS_TABLE
    value: "tickets"
  - name: TICKET_MESSAGES_TABLE
    value: "ticket_messages"
